version: '3.7'
volumes:
  ts-db:

services:
  ts-postgres:
    container_name: coffeeshop
    image: postgres:15.8-alpine
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coffeeshop
    volumes:
        - ts-db:/var/lib/postgresql/data
  #      - ./data:/var/lib/postgresql/data
        - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5438:5432"
